version: '2'
services:
 web:
   image: brettt89/silverstripe-web:7.1-platform
   working_dir: /var/www
   volumes:
    - ../www:/var/www/html
   ports:
    - "80:80"
 database:
   image: mariadb
   volumes:
    - ~/srv/docker/data/mysql/jorm/franklinlakes:/var/lib/mysql
   restart: always
   environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true

#volumes:
# db-data:
